#!/bin/bash
# 
# yvalue [arguments]  pwlfile
#

USAGE="\n
usage: \n
yvalue [options] < file # print the y value of the waveform at given time\n
	-t <time> # specify the sample time\n
	-h        #print this usage message\n"

while getopts "t:h" arg
do
    case $arg in
    	t) export TIME=$OPTARG ;;
	h) echo -e $USAGE; exit 0;;
	:) exit 1 ;;
	?) echo -e $USAGE; exit 0;;
    esac
done

awk '
    BEGIN {
	TIME=ENVIRON["TIME"]
    }

    // {
    	t2 = t; t = $1
    	v2 = v; v = $2

       if (t2 <= TIME && t >= TIME) {
	    if (!printed) {
	       if (t2 == TIME) {
		    printf("%12.12g %12.12g\n", TIME, v2);
	       } else if (t == TIME) {
		    printf("%12.12g %12.12g\n", TIME, v);
	       } else {
		    val = (v2 + (v-v2)*(TIME-t2)/(t-t2));
		    #print t2, v2, t, v, TIME
		    printf("%12.12g %12.12g\n", TIME, val);
	       }
	       printed++
	    }
        }
    }

    END {
    	if (!printed) {
	    print "time out of bounds" >"/dev/stderr"
	}
    }
'

